### ISSUE TITLE
5x slower startup that common spring context loader

### ISSUE THREAD

**Issue by ktor** [tmoreira2020/spring-boot-liferay-portlet#2]
Hi Thiago,

another issue we've encountered with the setup is startup time of a single portlet. On our hardware it's  around ~25s in comparison to common common spring context loader that with the same portlet takes aroung ~5s.

**Comment by tmoreira2020** [comment]
Liferay is a huge platform that takes time to fully starts and warms up, 25 seconds isn't bad at all.

**Comment by ktor** [comment]
Sure, I just wanted you to know.
